version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${GEACCO_ROOT_PASSWORD}
      MYSQL_DATABASE: ${GEACCO_DATABASE}
      MYSQL_USER: ${GEACCO_USER}
      MYSQL_PASSWORD: ${GEACCO_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./data:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - "5672"
        - "15672"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  app:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - "db:db"
  scheduler:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    command: celery -A src beat -l debug --scheduler django_celery_beat.schedulers:DatabaseScheduler
    links:
      - "db:db"
  worker:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    command: celery -A src worker --loglevel=debug
    links:
      - "db:db"
