# Generated by Django 4.2.3 on 2023-07-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_domaintask_document_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaintask',
            name='output_file',
            field=models.FileField(blank=True, upload_to='files/output'),
        ),
    ]
