# Generated by Django 4.2.3 on 2023-07-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_domaintask_output_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtasks',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
    ]
